## This file serves as Data testing module

[] Check how Powerplants are distributed <br/>
[] Add Impact radius <br/>
[] Add Renewability of production as feature

In [28]:
import pandas as pd 
import matplotlib.pyplot as plt

In [29]:
df = pd.read_csv("../data/global_power_plant_database.csv")
df.head()

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,fuel1,fuel2,fuel3,...,owner,source,url,geolocation_source,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,estimated_generation_gwh
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33,32,65,Hydro,NaN,NaN,...,NaN,GEODB,http://globalenergyobservatory.org,GEODB,"2,017",NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66,35,69,Hydro,NaN,NaN,...,NaN,GEODB,http://globalenergyobservatory.org,GEODB,"2,017",NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100,35,70,Hydro,NaN,NaN,...,NaN,GEODB,http://globalenergyobservatory.org,GEODB,"2,017",NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,Nangarhar (Darunta) Hydroelectric Power Plant ...,GEODB0040536,12,34,70,Hydro,NaN,NaN,...,NaN,GEODB,http://globalenergyobservatory.org,GEODB,"2,017",NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,Northwest Kabul Power Plant Afghanistan,GEODB0040540,42,35,69,Gas,NaN,NaN,...,NaN,GEODB,http://globalenergyobservatory.org,GEODB,"2,017",NaN,NaN,NaN,NaN,NaN

In [ ]:
list(df.columns)

['country',
 'country_long',
 'name',
 'gppd_idnr',
 'capacity_mw',
 'latitude',
 'longitude',
 'fuel1',
 'fuel2',
 'fuel3',
 'fuel4',
 'commissioning_year',
 'owner',
 'source',
 'url',
 'geolocation_source',
 'year_of_capacity_data',
 'generation_gwh_2013',
 'generation_gwh_2014',
 'generation_gwh_2015',
 'generation_gwh_2016',
 'estimated_generation_gwh']

In [35]:
df.groupby("fuel1").agg(
    count = ("fuel1", "size"),
    total_mw=("capacity_mw", "sum")
).reset_index()

             fuel1  count  total_mw
0          Biomass   1290    30,457
1             Coal   2172 1,860,150
2     Cogeneration     43     4,575
3              Gas   3068 1,179,516
4       Geothermal    186    12,551
5            Hydro   7034 1,045,867
6          Nuclear    199   408,613
7              Oil   2925   477,972
8            Other     36     2,190
9          Petcoke      8       486
10           Solar   5424    57,645
11         Storage     39       349
12           Waste   1143    20,489
13  Wave and Tidal     10       552
14            Wind   5084   232,800